### ISSUE TITLE
Can't execute bss program

### ISSUE THREAD

**Issue by NadSo** [balle/bluediving#2]
Hello 
I am trying to test the bss-0.8 on my ubuntu without success

![bss_error](https://user-images.githubusercontent.com/29726124/31379376-5da0858c-adae-11e7-85fa-697182d39011.png)

**Comment by balle** [comment]
Hi,

sorry for the late reply I am quite busy the last weeks. On my Fedora 26 it compiles with some warning, but runs as expected. Did you forget to install the bluez development files?

Best,

Basti

**Comment by NadSo** [comment]
Hello, 
Can you please help me? I am actually more interested about fuzzing BLE but I don't know how to build malformed data packets by using for example bluez?

**Comment by balle** [comment]
Hi,

I never coded a Bluetooth fuzzing tool myself, but you can read the
source of bss or use Scapy or my Bluetooth snippets (https://github.com
/balle/bluetooth-snippets) as a start.

Be aware that fuzzing Bluetooth packets may only crash the firmware of
your Bluetooth dongle. 

It's not like fuzzing TCP/IP as Bluetooth packets are in reality
constructed and send by the dongle. From the OS you cannot get lower
than HCI.

Best,

Basti

**Comment by NadSo** [comment]
Hello Balle, I am talking about BLE (bluetooth low energy) not classic bluetooth. Since there is a huge difference between both of them as far as I know. 
I am to modify bluez source code in order to fuzz
