### ISSUE TITLE
Implementation in python

### ISSUE THREAD

**Issue by HardipinderS** [balle/bluediving#4]
Hi there, 

I saw your project Linux basics of hacking and read README and felt it is a good project. If it is ok with you guys, I was hoping to implement the project in python. 

I was hoping to some context and idea on where and how to get started. Let me know if I could get some guidance.

**Comment by balle** [comment]
Hi,

there already is a Python implementation of Bluediving. Have a look at
https://tools.kali.org/wireless-attacks/bluemaho

Best,
Basti
